FROM python:3.9-slim

WORKDIR /app

# Copier les fichiers requirements depuis le dossier api
COPY ./api/requirements.fastapi.txt ./requirements.txt

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copier tout le contenu du dossier api vers le dossier de travail
COPY ./api /app

# Commande pour lancer l'application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
